* Question :drill:
Why Parallel Processing?

** Answer
- Computation requirements are ever increasing
  - simulations
  - internet
  - finance
  - mining
  - etc.
- Silicon based (sequential) architectures reaching their limits in processing capabilities (clock speed) as they are constrained by:
  - the speed of light VS thermodynamics
  - quantum computing


* Question :drill:
What does FLOPS mean?

** Answer
FLOPS: floating-point operations per second

It's a measure of computer performance.


* Question :drill:
Give 4 applications of the supercomputer Earth Simulator 2?

** Answer
- Ocean - Atmosphere interactions
- Deep current simulation in the Atlantic
- Simulation of tuna moves around Japan
- Simulation of Galaxies (model the growth of galaxies 300 million years after the Big Bang until now)



* Question :drill:
What is the Top 500?

** Answer
A benchmark and ranking for the world's fastest super computers. Since 1993 a list of computers ranked by their performance on the Linpack Bench.

* Question :drill:
In the top 500, how do supercomuters are evaluated?

** Answer
We use the Rmax and Rpeak on the LINPACK Benchmark.
- The Rpeak score describes its theoritical peak performance.
- The Rmax score describes its maximal achieved performance.

Both of these measures are in TFlops/s 


* Question :drill:
What is the first supercomputer?

** Answer
The first machine referred as a supercomputer is the IBM Naval Ordonance Research Calculator.
It was used at Columbia University from 1954 to 1963 to calculate missile trajectories.

about 15000 operations per seconds.


* Question :drill:
What are the differences between scalar, vector, superscalar?

** Answer
 
- The simplest processors are scalar. Each instruction typically manipulates one or two data items at a time.
- Each instruction executed by a vector processor operates simultaneously on many data items.
- A superscalar processor is sort of a mixture of both. Each instruction processes one data item, but there are multiple redundant 
 functional units within each CPU thus multiple insctructions can be processing separate data items concurrently.


* Question :drill:
What is the Flynn classification?

** Answer
Flynn proposed a classification of computer systems based on a number of instruction and data streams that can be processed simultaneously.

- SISD (Single Instruction and Single Data): conventional old computes
- SIMD (Single Instruction Multiple Data): Data parallel, vector computing machine
- MISD (Multiple Instruction Single Data): Systolic arrays - More of an intellectual exercice than a practical config. Not available commercially.
- MIMD (Multiple Instruction Multiple Data): General purpose machines

* Question :drill:
What is the limitation of SSID?

** Answer
The speed is limited by the rate at which computers can transfer information internally.














* Question :drill:
Can science predict everything, calculate everything, demonstrate everything?

** Answer

No... Despite massive media communication on the fact that Science will explain everything. Mathematicians and Physicists have discovered and demonstrated
several *irreductible limits* to the universal knowledge.

- Godel's incompleteness theorems are among the the first examples of fundamental limits of mathematics.
- There are also cognitive and ontological limits (in connection with the study of being, its modalities and its properties). It is indeed impossible to calculate some 
mathematical/physical objects and even to know if some exists. 
- Chaotic systems, which can only be studied by simulation, pose a predictive limit, it is not possible to determine the state of the system beyond a limited future. 

* Question :drill:
What is emrgence?

** Answer
The emergence evokes the idea of an unveiling, an apparition that takes shape, but was somewhat already there, under the appearance still elusive or completely hidden.

This is the case or emerging land (hidden below water) or the case of an iceberg. 


* Question :drill:
What are the limits of Science in explaining everything ?

** Answer
These limits fall into 4 categories: 

1. Predictive limits: show the impossibility of predicting certain phenomenona with an arbitrary precision over an indefinite time scale.
2. Cognitive limits: related to the existence of domains that remain beyond the reach of knowledge. Such limits appear in mathematics in the study of perfectly defined bu incalculable numbers and of numbers that can oonly be determined witha finite number of decimals (PI, PHI etc.)
3. The constructive limit: that relate to the impossibility of constructing a scientific discourse which escapes all doubt and which relies on a sure fondation. 
4. The ontological limits: that eliminate some conceptual entities by showing their inconsistency or by locating them outsite the field of apprehension if the scientific discourse. This is the case in quantum physics with the privileged role of the observer, or in mathematics with the question of the existence or not of certain objects.



